IMAGE                                                                     CREATED         CREATED BY                                                                                                                                                        SIZE      COMMENT
sha256:eadd4c91ae7ad70badc12e3ba2510f60e914cb56f6f1181e1ad8d77521e65338   6 weeks ago     /bin/sh -c #(nop) COPY dir:41a6e504065ccd3fb1d1141583313912c90e0e88a67e6b9cb6b2dfd5d8c40608 in /vllm-workspace/qwen2-72b-instruct-int4                            41.6GB
<missing>                                                                 3 months ago    ENTRYPOINT ["python3" "-m" "vllm.entrypoints.openai.api_server"]                                                                                                  0B        buildkit.dockerfile.v0
<missing>                                                                 3 months ago    ENV VLLM_USAGE_SOURCE=production-docker-image                                                                                                                     0B        buildkit.dockerfile.v0
<missing>                                                                 3 months ago    RUN /bin/sh -c pip install accelerate hf_transfer modelscope # buildkit                                                                                           308MB     buildkit.dockerfile.v0
<missing>                                                                 3 months ago    RUN /bin/sh -c pip install /usr/src/flash-attention-v2/*.whl --no-cache-dir # buildkit                                                                            406MB     buildkit.dockerfile.v0
<missing>                                                                 3 months ago    RUN /bin/sh -c pip install dist/*.whl --verbose # buildkit                                                                                                        6.93GB    buildkit.dockerfile.v0
<missing>                                                                 3 months ago    RUN /bin/sh -c ldconfig /usr/local/cuda-12.1/compat/ # buildkit                                                                                                   21.1kB    buildkit.dockerfile.v0
<missing>                                                                 3 months ago    RUN /bin/sh -c apt-get update -y     && apt-get install -y python3-pip git vim # buildkit                                                                         469MB     buildkit.dockerfile.v0
<missing>                                                                 3 months ago    WORKDIR /vllm-workspace                                                                                                                                           0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility                                                                                                                    0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NVIDIA_VISIBLE_DEVICES=all                                                                                                                                    0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    COPY NGC-DL-CONTAINER-LICENSE / # buildkit                                                                                                                        17.3kB    buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                                                 0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                   0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    RUN |1 TARGETARCH=amd64 /bin/sh -c echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf     && echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf # buildkit                    46B       buildkit.dockerfile.v0
<missing>                                                                 9 months ago    RUN |1 TARGETARCH=amd64 /bin/sh -c apt-get update && apt-get install -y --no-install-recommends     cuda-cudart-12-1=${NV_CUDA_CUDART_VERSION}     ${NV_CUDA_COMPAT_PACKAGE}     && rm -rf /var/lib/apt/lists/* # buildkit                    150MB     buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV CUDA_VERSION=12.1.0                                                                                                                                           0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    RUN |1 TARGETARCH=amd64 /bin/sh -c apt-get update && apt-get install -y --no-install-recommends     gnupg2 curl ca-certificates &&     curl -fsSLO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/${NVARCH}/cuda-keyring_1.0-1_all.deb &&     dpkg -i cuda-keyring_1.0-1_all.deb &&     apt-get purge --autoremove -y curl     && rm -rf /var/lib/apt/lists/* # buildkit                 10.6MB    buildkit.dockerfile.v0
<missing>                                                                 9 months ago    LABEL maintainer=NVIDIA CORPORATION <cudatools@nvidia.com>                                                                                                        0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ARG TARGETARCH                                                                                                                                                    0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NV_CUDA_COMPAT_PACKAGE=cuda-compat-12-1                                                                                                                       0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NV_CUDA_CUDART_VERSION=12.1.55-1                                                                                                                              0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526   0B        buildkit.dockerfile.v0
<missing>                                                                 9 months ago    ENV NVARCH=x86_64                                                                                                                                                 0B        buildkit.dockerfile.v0
<missing>                                                                 10 months ago   /bin/sh -c #(nop)  CMD ["/bin/bash"]                                                                                                                              0B
<missing>                                                                 10 months ago   /bin/sh -c #(nop) ADD file:63d5ab3ef0aab308c0e71cb67292c5467f60deafa9b0418cbb220affcd078444 in /                                                                  77.8MB
<missing>                                                                 10 months ago   /bin/sh -c #(nop)  LABEL org.opencontainers.image.version=22.04                                                                                                   0B
<missing>                                                                 10 months ago   /bin/sh -c #(nop)  LABEL org.opencontainers.image.ref.name=ubuntu                                                                                                 0B
<missing>                                                                 10 months ago   /bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH                                                                                                                       0B
<missing>                                                                 10 months ago   /bin/sh -c #(nop)  ARG RELEASE                                                                                                                                    0B